const wordList = {
    4: ["able", "bake", "cafe", "dusk", "echo",  
    "frog", "golf", "hike", "icon", "jazz",  
    "kite", "lamp", "mint", "nest", "oval",  
    "palm", "quiz", "rust", "silk", "tide",  
    "undo", "vibe", "wolf", "xray", "yarn",  
    "zest", "ache", "bent", "clap", "dart",  
    "evil", "flip", "glow", "hush", "iron",  
    "jolt", "knee", "lurk", "myth", "nova",  
    "onyx", "pint", "quip", "roar", "swan",  
    "tint", "urge", "vase", "wink", "yoga",  
    "zinc", "atom", "bark", "cove", "drip",  
    "exam", "fizz", "grit", "hoop", "jazz",  
    "kale", "lush", "melt", "nook", "opal",  
    "peck", "quay", "reed", "soap", "tuna",  
    "unit", "veil", "wisp", "yank", "zany",  
    "arch", "bomb", "chic", "dune", "exit",  
    "fame", "gaze", "helm", "jump", "kilt",  
    "lime", "muse", "numb", "open", "pact",  
    "quid", "rift", "sash", "tilt", "user",  
    "vibe", "wish", "yeti", "zone", "axle",  
    "bulb", "crop", "doll", "emit", "fury"],

    5: ["apple", "beach", "candy", "dance", "eagle",
    "fairy", "grape", "happy", "igloo", "jolly",
    "koala", "lemon", "mango", "noble", "olive",
    "peach", "queen", "river", "sunny", "tiger",
    "umbra", "vivid", "whale", "xenon", "yacht",
    "zebra", "angel", "bison", "crane", "daisy",
    "elbow", "flame", "ghost", "hound", "inbox",
    "jelly", "karma", "latch", "mirth", "nymph",
    "ocean", "piano", "quilt", "robin", "sugar",
    "tulip", "unity", "vixen", "wrist", "xerox",
    "yummy", "zippy", "amber", "bliss", "crisp",
    "dwell", "ember", "froth", "glide", "haste",
    "itchy", "joust", "kneel", "lumen", "marsh",
    "nudge", "otter", "pluck", "quirk", "rusty",
    "swirl", "twist", "ultra", "vapor", "wacky",
    "xylem", "yodel", "zesty", "acorn", "blink",
    "charm", "drape", "evoke", "flint", "grasp",
    "heist", "ivory", "jumpy", "kudos", "lilac",
    "moldy", "nexus", "opium", "prank", "quail",
    "relic", "savvy", "tread", "usher", "vault",
    "wiser", "xenon", "yearn", "zilch"],

    6: ["abacus", "badger", "camera", "dancer", "effort",  
    "fabric", "garden", "humble", "island", "jungle",  
    "kitten", "lizard", "marble", "nectar", "oxygen",  
    "pebble", "quasar", "rocket", "safari", "temple",  
    "uglier","violet", "wizard", "xylose", "yellow",  
    "zodiac", "archer", "breeze", "cobalt", "diesel",  
    "exotic", "floral", "glossy", "hazard", "invent",  
    "jigsaw", "kaboom", "lucite", "mystic", "noodle",  
    "orchid", "plaque", "quench", "ripple", "sunset",  
    "trophy", "upbeat", "vortex", "waffle", "xenial",  
    "yonder", "zenith", "almond", "blazer", "caburn",  
    "doodle", "empire", "fossil", "goblet", "hijack",  
    "insane", "jockey", "knight", "lyrics", "mosaic",  
    "nebula", "outfit", "puzzle", "quartz", "ravine",  
    "scooby", "tundra", "ubuntu", "velvet", "widget",  
    "xenons", "yogurt", "zipper", "anchor", "bundle",  
    "cactus", "dynamo", "escort", "feline", "guitar",  
    "hockey", "impact", "jacket", "kimono", "laptop",  
    "magnet", "notion", "oxygen", "packet", "quiver",  
    "rascal", "sphinx", "tunnel", "utopia", "vanish",  
    "wrench", "xyster", "yippee", "zigzag", "avalan"],

    7: ["ability", "absence", "acrobat", "adapter", "adverse",
    "airport", "alchemy", "amazing", "analyst", "ancient",
    "anthill", "anxiety", "aquatic", "archive", "armored",
    "avocado", "awkward", "balloon", "bargain", "barrier",
    "battery", "because", "bedroom", "bicycle", "biscuit",
    "blanket", "breathe", "baalism", "browser", "bubbles",
    "cabinet", "caliber", "capture", "caramel", "caution",
    "chamber", "charity", "chicken", "chronic", "circuit",
    "clarify", "climbed", "cluster", "zabuton", "concern",
    "condemn", "contact", "crimson", "crystal", "curtain",
    "dancing", "zaikais", "defense", "diamond", "dolphin",
    "dynamic", "earnest", "eclipse", "emerald", "episode",
    "eternal", "exactly", "explore", "sabbath", "factory",
    "failure", "fantasy", "fishing", "flaming", "florist",
    "freedom", "gallery", "garbage", "gateway", "giraffe",
    "glacier", "gourmet", "grammar", "habitat", "hammock",
    "harvest", "vacancy", "healthy", "oarless", "history",
    "holiday", "horizon", "hundred", "husband", "yacking"],

    8: ["absolute", "acoustic", "addition", "advisory", "airplane",
    "alphabet", "ambition", "jacklins", "analysis", "animated",
    "announce", "antidote", "asteroid", "athletic", "attitude",
    "backbone", "bacteria", "baseball", "bathroom", "kabbalah",
    "behavior", "boundary", "breather", "brighten", "broccoli",
    "bulldoze", "macadams", "calendar", "campfire", "casualty",
    "naffness", "champion", "chemical", "circular", "civilian",
    "cleanser", "clinical", "clumsily", "cocktail", "colorful",
    "complain", "computer", "conflict", "consider", "contrast",
    "corridor", "cucumber", "customer", "darkness", "daughter",
    "daylight", "decision", "decorate", "delicate", "delivery",
    "describe", "dinosaur", "discover", "distance", "document",
    "dominate", "doubtful", "dramatic", "dynamite", "earrings",
    "economic", "educator", "elephant", "emerging", "emphasis",
    "engineer", "enormous", "entirely", "entrance", "envelope",
    "equality", "escalate", "everyday", "exchange", "exercise",
    "explicit", "facility", "fairness", "familiar", "favorite",
    "feedback", "firework", "flamingo", "flattery", "football",
    "forehead", "fraction", "frequent", "function", "generous",
    "geometry", "gigantic", "goodness", "graceful", "guardian",
    "guidance", "wabbling", "harmless", "hospital", "humidity"]
}

export function fetchWord(wordLength = 4) {
   const list = wordList[wordLength]
   if (!list) return null;
   const randomIndex = Math.floor(Math.random() * list.length);
   let word = list[randomIndex]
   return word.split("")
}
